---
title: "project2 Tutorial"
author: "Yuchi Hsieh"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{project2 Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup, echo=FALSE}
library(ggplot2)
penguins_df <- load("/Users/carrie/Desktop/stat302/projects/project2/pipeline/data/my_penguins.rda")
source("/Users/carrie/Desktop/stat302/projects/project2/pipeline/code/my_rf_cv.R")
```

## my_rf_cv

```{r}
iter <- c(2, 5, 10)
rf_result <- data.frame(matrix(ncol = 3, nrow = 30))
rf_boxplot <- data.frame(matrix(ncol = 2, nrow = 90))
for (i in 1:3) {
  k <- iter[i]
  for (j in 1:30) {
    ans <- my_rf_cv(k)
    rf_result[j,i] <- ans
    rf_boxplot[(i-1)*30+j, 1] <- ans
    rf_boxplot[(i-1)*30+j, 2] <- k
  }
}
colnames(rf_result) <- c("k = 2", "k = 5", "k = 10")
colnames(rf_boxplot) <- c("CV", "k")
ggplot(rf_boxplot, aes(x = k, y = CV, group = k)) +
  geom_boxplot() +
  labs(title = "Simulations of k = 2, 5, 10")
ggsave("../output/figures/boxplot.png")
result_table <- data.frame(matrix(ncol = 2, nrow = 3))
result_table[1,1] <- mean(rf_result[, 1])
result_table[2,1] <- mean(rf_result[, 2])
result_table[3,1] <- mean(rf_result[, 3])
result_table[1,2] <- sd(rf_result[, 1])
result_table[2,2] <- sd(rf_result[, 2])
result_table[3,2] <- sd(rf_result[, 3])
colnames(result_table) <- c("mean", "sd")
rownames(result_table) <- c("k = 2", "k = 5", "k = 10")
result_table
write.csv(rf_result, "../output/results/simulation.csv")
saveRDS(result_table, "/Users/carrie/Desktop/stat302/projects/project2/pipeline/output/results/summary.rds")
```

When k = 5, it has the smallest mean. As k increases, the standard deviation becomes bigger and bigger. I think it's because when k is greater, the data is split into more trees causing larger standard deviations across trees.





